//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuleConfiguration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RuleConfiguration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        internal static string ActivitySelectContext {
            get {
                return ResourceManager.GetString("ActivitySelectContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Add Rule...&gt;.
        /// </summary>
        internal static string AddRule {
            get {
                return ResourceManager.GetString("AddRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open clipboard..
        /// </summary>
        internal static string CannotOpenClipboard {
            get {
                return ResourceManager.GetString("CannotOpenClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of catalog material model....
        /// </summary>
        internal static string CatalogMaterialModelNameItem {
            get {
                return ResourceManager.GetString("CatalogMaterialModelNameItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        internal static string CatalogSelectContext {
            get {
                return ResourceManager.GetString("CatalogSelectContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore this item.
        /// </summary>
        internal static string ClickToBlock {
            get {
                return ResourceManager.GetString("ClickToBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not ignore this item.
        /// </summary>
        internal static string ClickToUnblock {
            get {
                return ResourceManager.GetString("ClickToUnblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to remove from parent container.
        /// </summary>
        internal static string ClickUncontain {
            get {
                return ResourceManager.GetString("ClickUncontain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to last valid value..
        /// </summary>
        internal static string ConvertToLastValidValue {
            get {
                return ResourceManager.GetString("ConvertToLastValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as XAML.
        /// </summary>
        internal static string CopyAsXaml {
            get {
                return ResourceManager.GetString("CopyAsXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyNamedRuleDisplayName {
            get {
                return ResourceManager.GetString("CopyNamedRuleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as Subrule.
        /// </summary>
        internal static string CopyRulePointDisplayName {
            get {
                return ResourceManager.GetString("CopyRulePointDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Subrule.
        /// </summary>
        internal static string CreateNewSubruleDisplayName {
            get {
                return ResourceManager.GetString("CreateNewSubruleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create new subrule..
        /// </summary>
        internal static string CreateNewSubruleFailed {
            get {
                return ResourceManager.GetString("CreateNewSubruleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Rule.
        /// </summary>
        internal static string CreateRuleContentDisplayName {
            get {
                return ResourceManager.GetString("CreateRuleContentDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string CutNamedRuleDisplayName {
            get {
                return ResourceManager.GetString("CutNamedRuleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subrule.
        /// </summary>
        internal static string DefaultNewSubruleName {
            get {
                return ResourceManager.GetString("DefaultNewSubruleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string DefaultStyleName {
            get {
                return ResourceManager.GetString("DefaultStyleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Subrule.
        /// </summary>
        internal static string DeleteNamedRuleDisplayName {
            get {
                return ResourceManager.GetString("DeleteNamedRuleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Rule.
        /// </summary>
        internal static string DeleteRulePointDisplayName {
            get {
                return ResourceManager.GetString("DeleteRulePointDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter Types.
        /// </summary>
        internal static string DelimiterTypeSelectorContext {
            get {
                return ResourceManager.GetString("DelimiterTypeSelectorContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;{0}&apos; is duplicate..
        /// </summary>
        internal static string DuplicateNameExists {
            get {
                return ResourceManager.GetString("DuplicateNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Attributes.
        /// </summary>
        internal static string EnumerableAttributeSelectContext {
            get {
                return ResourceManager.GetString("EnumerableAttributeSelectContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equals.
        /// </summary>
        internal static string Equal {
            get {
                return ResourceManager.GetString("Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create rule. Exception: {0}.
        /// </summary>
        internal static string FailedToCreateRule {
            get {
                return ResourceManager.GetString("FailedToCreateRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete rule in rule point &apos;{0}&apos;..
        /// </summary>
        internal static string FailedToDelete {
            get {
                return ResourceManager.GetString("FailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Attributes.
        /// </summary>
        internal static string FeatureAttributeSelectContext {
            get {
                return ResourceManager.GetString("FeatureAttributeSelectContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details for {0}.
        /// </summary>
        internal static string FeatureClassDetailSelectContextName {
            get {
                return ResourceManager.GetString("FeatureClassDetailSelectContextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Classes.
        /// </summary>
        internal static string FeatureClassSelectContext {
            get {
                return ResourceManager.GetString("FeatureClassSelectContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (filter applied).
        /// </summary>
        internal static string FilterApplied {
            get {
                return ResourceManager.GetString("FilterApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        internal static string FunctionSelectContext {
            get {
                return ResourceManager.GetString("FunctionSelectContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Details.
        /// </summary>
        internal static string GenericDetailSelectContextName {
            get {
                return ResourceManager.GetString("GenericDetailSelectContextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is more than.
        /// </summary>
        internal static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is at least.
        /// </summary>
        internal static string GreaterThanOrEqual {
            get {
                return ResourceManager.GetString("GreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is less than.
        /// </summary>
        internal static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is at most.
        /// </summary>
        internal static string LessThanOrEqual {
            get {
                return ResourceManager.GetString("LessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input &quot;{0}&quot; can&apos;t be converted to numeric value..
        /// </summary>
        internal static string LiteralNumericValidateError {
            get {
                return ResourceManager.GetString("LiteralNumericValidateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material List Generation.
        /// </summary>
        internal static string MaterialListGeneration {
            get {
                return ResourceManager.GetString("MaterialListGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Attributes.
        /// </summary>
        internal static string ModelAttributeSelectContext {
            get {
                return ResourceManager.GetString("ModelAttributeSelectContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be empty..
        /// </summary>
        internal static string NameCannotBeEmpty {
            get {
                return ResourceManager.GetString("NameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subrules.
        /// </summary>
        internal static string NamedRuleSelectContext {
            get {
                return ResourceManager.GetString("NamedRuleSelectContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No Feature Attribute&gt;.
        /// </summary>
        internal static string NoFeatureAttribute {
            get {
                return ResourceManager.GetString("NoFeatureAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not equal to.
        /// </summary>
        internal static string NotEqual {
            get {
                return ResourceManager.GetString("NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators.
        /// </summary>
        internal static string OperatorSelectContext {
            get {
                return ResourceManager.GetString("OperatorSelectContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string PasteNamedRuleDisplayName {
            get {
                return ResourceManager.GetString("PasteNamedRuleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes?.
        /// </summary>
        internal static string PreClosingPrompt {
            get {
                return ResourceManager.GetString("PreClosingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when resolving errors. .
        /// </summary>
        internal static string ResolveExceptionMessage {
            get {
                return ResourceManager.GetString("ResolveExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;{0}&apos; contains illegal character..
        /// </summary>
        internal static string RuleNameContainsIllegalChar {
            get {
                return ResourceManager.GetString("RuleNameContainsIllegalChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string RuleStyle {
            get {
                return ResourceManager.GetString("RuleStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Validation.
        /// </summary>
        internal static string RuleValidation {
            get {
                return ResourceManager.GetString("RuleValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save rules. Exception: {0}..
        /// </summary>
        internal static string SaveErrorMessage {
            get {
                return ResourceManager.GetString("SaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        internal static string StyleSelectContext {
            get {
                return ResourceManager.GetString("StyleSelectContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style Symbols.
        /// </summary>
        internal static string StyleSymbolSelectContext {
            get {
                return ResourceManager.GetString("StyleSymbolSelectContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Attributes.
        /// </summary>
        internal static string TableAttributeSelectContext {
            get {
                return ResourceManager.GetString("TableAttributeSelectContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Name.
        /// </summary>
        internal static string TableSelectContext {
            get {
                return ResourceManager.GetString("TableSelectContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string UnitSelectContext {
            get {
                return ResourceManager.GetString("UnitSelectContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ( devices: {0}; alerts: {1}; notices: {2} ).
        /// </summary>
        internal static string ValidationGroupHeader {
            get {
                return ResourceManager.GetString("ValidationGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Alert.
        /// </summary>
        internal static string ValidationItemHeaderFailure {
            get {
                return ResourceManager.GetString("ValidationItemHeaderFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Ignored Message.
        /// </summary>
        internal static string ValidationItemHeaderIgnoredMessage {
            get {
                return ResourceManager.GetString("ValidationItemHeaderIgnoredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Ignored Notice.
        /// </summary>
        internal static string ValidationItemHeaderIgnoredWarning {
            get {
                return ResourceManager.GetString("ValidationItemHeaderIgnoredWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Message.
        /// </summary>
        internal static string ValidationItemHeaderMessage {
            get {
                return ResourceManager.GetString("ValidationItemHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Notice.
        /// </summary>
        internal static string ValidationItemHeaderWarning {
            get {
                return ResourceManager.GetString("ValidationItemHeaderWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Types.
        /// </summary>
        internal static string ValidationTypeSelectContext {
            get {
                return ResourceManager.GetString("ValidationTypeSelectContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Values.
        /// </summary>
        internal static string ValidValueSelectContext {
            get {
                return ResourceManager.GetString("ValidValueSelectContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writable Feature Attributes.
        /// </summary>
        internal static string WritableAttributeSelectContext {
            get {
                return ResourceManager.GetString("WritableAttributeSelectContext", resourceCulture);
            }
        }
    }
}
