//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autodesk.IM.Rule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autodesk.IM.Rule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abs.
        /// </summary>
        internal static string Abs {
            get {
                return ResourceManager.GetString("Abs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acos.
        /// </summary>
        internal static string Acos {
            get {
                return ResourceManager.GetString("Acos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string AddOperator {
            get {
                return ResourceManager.GetString("AddOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0}&apos; is empty..
        /// </summary>
        internal static string ArgumentExceptionMessage {
            get {
                return ResourceManager.GetString("ArgumentExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asin.
        /// </summary>
        internal static string Asin {
            get {
                return ResourceManager.GetString("Asin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atan.
        /// </summary>
        internal static string Atan {
            get {
                return ResourceManager.GetString("Atan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atan2.
        /// </summary>
        internal static string Atan2 {
            get {
                return ResourceManager.GetString("Atan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register rule point. The target location is not a rule point..
        /// </summary>
        internal static string CannotRegisterRulePoint {
            get {
                return ResourceManager.GetString("CannotRegisterRulePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ceil.
        /// </summary>
        internal static string Ceil {
            get {
                return ResourceManager.GetString("Ceil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule contains some errors.
        /// {0}.
        /// </summary>
        internal static string CommonRuleExceptionUserMessage {
            get {
                return ResourceManager.GetString("CommonRuleExceptionUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cos.
        /// </summary>
        internal static string Cos {
            get {
                return ResourceManager.GetString("Cos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cosh.
        /// </summary>
        internal static string Cosh {
            get {
                return ResourceManager.GetString("Cosh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string DivideOperator {
            get {
                return ResourceManager.GetString("DivideOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equals.
        /// </summary>
        internal static string Equal {
            get {
                return ResourceManager.GetString("Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An endless loop has been detected. It is usually caused by the rule directly or indirectly invoking itself..
        /// </summary>
        internal static string ExceedsMaxInvokeDepth {
            get {
                return ResourceManager.GetString("ExceedsMaxInvokeDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exp.
        /// </summary>
        internal static string Exp {
            get {
                return ResourceManager.GetString("Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute match activity.
        /// </summary>
        internal static string FailMatchValue {
            get {
                return ResourceManager.GetString("FailMatchValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create new subrule..
        /// </summary>
        internal static string FailToAddSubRule {
            get {
                return ResourceManager.GetString("FailToAddSubRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to floor.
        /// </summary>
        internal static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is more than.
        /// </summary>
        internal static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is at least.
        /// </summary>
        internal static string GreaterThanOrEqual {
            get {
                return ResourceManager.GetString("GreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is less than.
        /// </summary>
        internal static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is at most.
        /// </summary>
        internal static string LessThanOrEqual {
            get {
                return ResourceManager.GetString("LessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ln.
        /// </summary>
        internal static string Ln {
            get {
                return ResourceManager.GetString("Ln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mod.
        /// </summary>
        internal static string Mod {
            get {
                return ResourceManager.GetString("Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string MultiplyOperator {
            get {
                return ResourceManager.GetString("MultiplyOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subrule or sub rule point &apos;{0}&apos; does already exist..
        /// </summary>
        internal static string NamedRuleAlreadyExists {
            get {
                return ResourceManager.GetString("NamedRuleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subrule &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string NamedRuleNotExist {
            get {
                return ResourceManager.GetString("NamedRuleNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subrules.
        /// </summary>
        internal static string NamedRuleProviderDisplayName {
            get {
                return ResourceManager.GetString("NamedRuleProviderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subrules.
        /// </summary>
        internal static string NamedRuleProviderName {
            get {
                return ResourceManager.GetString("NamedRuleProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not.
        /// </summary>
        internal static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not equal.
        /// </summary>
        internal static string NotEqual {
            get {
                return ResourceManager.GetString("NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to power.
        /// </summary>
        internal static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your string expression....
        /// </summary>
        internal static string PromptEditingString {
            get {
                return ResourceManager.GetString("PromptEditingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remainder.
        /// </summary>
        internal static string Remainder {
            get {
                return ResourceManager.GetString("Remainder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to round.
        /// </summary>
        internal static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in rule: {0}
        ///Detailed information: {1}.
        /// </summary>
        internal static string RuleException {
            get {
                return ResourceManager.GetString("RuleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign.
        /// </summary>
        internal static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sin.
        /// </summary>
        internal static string Sin {
            get {
                return ResourceManager.GetString("Sin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sinh.
        /// </summary>
        internal static string Sinh {
            get {
                return ResourceManager.GetString("Sinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sqrt.
        /// </summary>
        internal static string Sqrt {
            get {
                return ResourceManager.GetString("Sqrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string SubtractOperator {
            get {
                return ResourceManager.GetString("SubtractOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tan.
        /// </summary>
        internal static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trunc.
        /// </summary>
        internal static string Trunc {
            get {
                return ResourceManager.GetString("Trunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exclusive or.
        /// </summary>
        internal static string Xor {
            get {
                return ResourceManager.GetString("Xor", resourceCulture);
            }
        }
    }
}
